import localFont from "next/font/local";
import "./globals.css";
import {GlobalProvider} from "@/app/GlobalContext";
import Link from "next/link";
import {NotificationProvider} from "@/app/NotificationContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <NotificationProvider>
      <GlobalProvider>
        {children}
      </GlobalProvider>
      </NotificationProvider>
      </body>
    </html>
  );
}
